### ISSUE TITLE
DBに接続できなくてアプリケーションの起動中にエラー終了する

### ISSUE THREAD

**Issue by hikuohiku** [gdsc-tmu/InfoLinkAPI#34]
`main.go`の`main`関数内でDBに接続できずエラー終了してます（24行目）

`mysql-container`内のシェルにアタッチしてmysqlを操作することはできているので，接続の設定の問題かな？と思ってます．エラーもconnection refusedだし

```
❯ docker compose up --build
[+] Building 47.7s (45/45) FINISHED                                                                                                                     docker:default
 => [go internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 1.39kB                                                                                                                            0.0s
 => [go internal] load metadata for docker.io/library/alpine:latest                                                                                               1.7s
 => [test internal] load metadata for docker.io/library/golang:1.21                                                                                               1.7s
 => [test internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.39kB                                                                                                                            0.0s
 => [swag internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.39kB                                                                                                                            0.0s
 => [tidy internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.39kB                                                                                                                            0.0s
 => [go internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [tidy internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [swag internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [test internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [swag builder 1/7] FROM docker.io/library/golang:1.21@sha256:856073656d1a517517792e6cdd2f7a5ef080d3ca2dff33e518c8412f140fdd2d                                 0.0s
 => [go internal] load build context                                                                                                                              0.0s
 => => transferring context: 9.91kB                                                                                                                               0.0s
 => [go stage-4 1/5] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                                 0.0s
 => [tidy internal] load build context                                                                                                                            0.0s
 => => transferring context: 9.91kB                                                                                                                               0.0s
 => [test internal] load build context                                                                                                                            0.0s
 => => transferring context: 9.91kB                                                                                                                               0.0s
 => [swag internal] load build context                                                                                                                            0.0s
 => => transferring context: 9.91kB                                                                                                                               0.0s
 => CACHED [test builder 2/7] WORKDIR /app                                                                                                                        0.0s
 => CACHED [go builder 3/7] COPY go.mod ./                                                                                                                        0.0s
 => CACHED [go builder 4/7] COPY go.sum ./                                                                                                                        0.0s
 => CACHED [go builder 5/7] RUN go mod download                                                                                                                   0.0s
 => [go builder 6/7] COPY . .                                                                                                                                     0.0s
 => CACHED [tidy tidy 3/6] COPY go.mod ./                                                                                                                         0.0s
 => CACHED [tidy tidy 4/6] COPY go.sum ./                                                                                                                         0.0s
 => [tidy tidy 5/6] COPY . .                                                                                                                                      0.1s
 => [swag swagger 3/5] COPY . .                                                                                                                                   0.0s
 => [go builder 7/7] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .                                                                       13.5s
 => [swag swagger 4/5] RUN go install github.com/swaggo/swag/cmd/swag@latest                                                                                     29.3s
 => [tidy tidy 6/6] RUN go mod tidy                                                                                                                              13.2s
 => [tidy] exporting to image                                                                                                                                     1.4s
 => => exporting layers                                                                                                                                           1.4s
 => => writing image sha256:92ab966aa2588aeb0eb4894c4f21bde065000ff0f0b31e7c3a8d3d00abf9b673                                                                      0.0s
 => => naming to docker.io/library/infolinkapi-tidy                                                                                                               0.0s
 => CACHED [go stage-4 2/5] RUN apk --no-cache add ca-certificates                                                                                                0.0s
 => CACHED [go stage-4 3/5] WORKDIR /root/                                                                                                                        0.0s
 => CACHED [go stage-4 4/5] COPY --from=builder /app/main .                                                                                                       0.0s
 => CACHED [go stage-4 5/5] COPY --from=builder /app/docs /app/docs                                                                                               0.0s
 => [go] exporting to image                                                                                                                                       0.0s
 => => exporting layers                                                                                                                                           0.0s
 => => writing image sha256:e6f81313681c1bc201b77122c1ef0be6262af588c7b9827d19cc15048f704395                                                                      0.0s
 => => naming to docker.io/library/infolinkapi-go                                                                                                                 0.0s
 => CACHED [test builder 3/7] COPY go.mod ./                                                                                                                      0.0s
 => CACHED [test builder 4/7] COPY go.sum ./                                                                                                                      0.0s
 => CACHED [test builder 5/7] RUN go mod download                                                                                                                 0.0s
 => CACHED [test builder 6/7] COPY . .                                                                                                                            0.0s
 => CACHED [test builder 7/7] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .                                                               0.0s
 => CACHED [test tester 3/5] COPY --from=builder /go /go                                                                                                          0.0s
 => [test tester 4/5] COPY --from=builder /app /app                                                                                                               0.1s
 => [test tester 5/5] RUN go test -v ./...                                                                                                                       17.4s
 => [swag swagger 5/5] RUN swag init                                                                                                                             15.5s
 => [test] exporting to image                                                                                                                                     0.7s
 => => exporting layers                                                                                                                                           0.7s
 => => writing image sha256:d39021bbbb412628f95c98685e1f632f363d1c682e458f76978204c9aaa735c8                                                                      0.0s
 => => naming to docker.io/library/infolinkapi-test                                                                                                               0.0s
 => [swag] exporting to image                                                                                                                                     1.0s
 => => exporting layers                                                                                                                                           1.0s
 => => writing image sha256:ca1f3698ea821e08313a0c895c70717a8e1e2c7e5d0ba26ba8b0ad0eef7a9589                                                                      0.0s
 => => naming to docker.io/library/infolinkapi-swag                                                                                                               0.0s
[+] Running 6/5
 ✔ Network infolinkapi_default   Created                                                                                                                          0.1s 
 ✔ Container infolinkapi-test-1  Created                                                                                                                          0.1s 
 ✔ Container infolinkapi-tidy-1  Created                                                                                                                          0.1s 
 ✔ Container infolinkapi-swag-1  Created                                                                                                                          0.1s 
 ✔ Container mysql-container     Created                                                                                                                          0.1s 
 ✔ Container infolinkapi-go-1    Created                                                                                                                          0.0s 
Attaching to go-1, swag-1, test-1, tidy-1, mysql-container
tidy-1 exited with code 0
mysql-container  | 2024-03-21 10:22:07+09:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
mysql-container  | 2024-03-21 10:22:07+09:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql-container  | 2024-03-21 10:22:07+09:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
swag-1 exited with code 0
test-1 exited with code 0
go-1             | 
go-1             | 2024/03/21 01:22:08 /app/main.go:20
go-1             | [error] failed to initialize database, got error dial tcp 172.19.0.4:3306: connect: connection refused
go-1             | panic: データベースへの接続に失敗しましたdial tcp 172.19.0.4:3306: connect: connection refused
go-1             | 
go-1             | goroutine 1 [running]:
go-1             | main.main()
go-1             | 	/app/main.go:24 +0x554
mysql-container  | 2024-03-21T01:22:08.083851Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.28) starting as process 1
mysql-container  | 2024-03-21T01:22:08.096216Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
go-1 exited with code 2
mysql-container  | 2024-03-21T01:22:08.337485Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-container  | 2024-03-21T01:22:08.542354Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-container  | 2024-03-21T01:22:08.542429Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-container  | 2024-03-21T01:22:08.543968Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql-container  | 2024-03-21T01:22:08.567439Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql-container  | 2024-03-21T01:22:08.567468Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```

**Comment by hikuohiku** [comment]
ホストOSにインストールしたmysqlクライアントからコンテナ内のDBに接続できることを確認したので，`go`コンテナ側の接続設定とかそっち側なんじゃないかとにらんでますが，正しく設定されているように見えるのでもうわかんないです．

**Comment by hikuohiku** [comment]
これ気づいたんですが，ログ見るにDBの初期化が行われる前にアクセスしてしまっているっぽいですね
